backend:
  name: git-gateway
  branch: master

site_url: https://artopen.netlify.app
display_url: https://artopen.netlify.app
logo_url: /icons/ArtOpen-black.svg
publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: "strony"
    label: "Strony"
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "Home"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
          - {label: "Title", name: "title", widget: string}
          - {label: "Heading", name: "heading", widget: string}
          - {label: "Keywords", name: "keywords", widget: "list"}
          - {label: "Meta Title", name: "meta_title", widget: "string"}
          - {label: "Meta Description", name: "meta_description", widget: "text"}

      - file: "src/pages/o-nas/index.md"
        label: "O nas"
        name: "O nas"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Meta Title", name: "meta_title", widget: "string"}
          - {label: "Meta Description", name: "meta_description", widget: "text"}
          - {label: "Keywords", name: "keywords", widget: "list"}

      - file: "src/pages/kontakt/index.md"
        label: "Kontakt"
        name: "Kontakt"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: "Meta Title", name: "meta_title", widget: "string"}
          - {label: "Meta Description", name: "meta_description", widget: "text"}
          - {label: "Keywords", name: "keywords", widget: "list"}

      - file: "src/pages/polityka-prywatnosci/index.md"
        label: "Polityka prywatności"
        name: "Polityka prywatnosci"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "policy-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Meta Title", name: "meta_title", widget: "string"}
          - {label: "Meta Description", name: "meta_description", widget: "text"}

      - file: "src/pages/katalogi/index.md"
        label: "Katalogi"
        name: "Katalogi"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "catalogs-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Meta Title", name: "meta_title", widget: "string"}
          - {label: "Meta Description", name: "meta_description", widget: "text"}
          - {label: "Keywords", name: "keywords", widget: "list"}

      - file: "src/pages/praca/index.md"
        label: "Praca"
        name: "Praca"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "work-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Meta Title", name: "meta_title", widget: "string"}
          - {label: "Meta Description", name: "meta_description", widget: "text"}
          - {label: "Keywords", name: "keywords", widget: "list"}

      - file: "src/pages/kreator-kalendarzy/index.md"
        label: "Kreator"
        name: "Kreator"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "kreator-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Meta Title", name: "meta_title", widget: "string"}
          - {label: "Meta Description", name: "meta_description", widget: "text"}
          - {label: "Keywords", name: "keywords", widget: "list"}

  - name: "Blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "article-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Cover", name: "cover", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Keywords", name: "keywords", widget: "list"}
      - {label: "Meta Title", name: "meta_title", widget: "string"}
      - {label: "Meta Description", name: "meta_description", widget: "text"}

  - name: "Portfolio"
    label: "Portfolio"
    folder: "src/pages/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "gallery-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Cover", name: "cover", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Keywords", name: "keywords", widget: "list"}
      - {label: "Meta Title", name: "meta_title", widget: "string"}
      - {label: "Meta Description", name: "meta_description", widget: "text"}
      - {label: "Category", name: "category", widget: "string"}

  - name: "Oferta"
    label: "Oferta"
    folder: "src/pages/oferta"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "offer-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "desc", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Icon", name: "icon", widget: "image"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Cover", name: "cover", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Keywords", name: "keywords", widget: "list"}
      - {label: "Meta Title", name: "meta_title", widget: "string"}
      - {label: "Meta Description", name: "meta_description", widget: "text"}
